// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, hashed_password, full_name, email
) VALUES (
    $1, $2, $3, $4
)
RETURNING username, full_name, created_at, hashed_password, password_changed_at, email
`

type CreateUserParams struct {
	Username       string `json:"username"`
	HashedPassword string `json:"hashedPassword"`
	FullName       string `json:"fullName"`
	Email          string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.HashedPassword,
		arg.FullName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.CreatedAt,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.Email,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, full_name, created_at, hashed_password, password_changed_at, email FROM users
WHERE username = $1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.CreatedAt,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.Email,
	)
	return i, err
}
